name: Prebuild

on: push

jobs:
  prebuild-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: yarn --frozen-lockfile
    - run: yarn prebuild
    - uses: actions/upload-artifact@v3
      with:
        name: windows
        path: prebuilds

  prebuild-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: |
        sudo apt-get update
        sudo apt-get install -y libxcb1-dev
    - run: yarn --frozen-lockfile
    - run: yarn prebuild
    - uses: actions/upload-artifact@v3
      with:
        name: linux
        path: prebuilds

  prebuild-darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: yarn --frozen-lockfile
    - run: yarn prebuild --arch x64
    - run: yarn prebuild --arch arm64
    - uses: actions/upload-artifact@v3
      with:
        name: darwin
        path: prebuilds

  build-package:
    needs:
    - prebuild-windows
    - prebuild-linux
    - prebuild-darwin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: windows
        path: prebuilds
    - uses: actions/download-artifact@v3
      with:
        name: linux
        path: prebuilds
    - uses: actions/download-artifact@v3
      with:
        name: darwin
        path: prebuilds
    - uses: actions/setup-node@v3
    - run: yarn --frozen-lockfile --ignore-scripts
    - run: yarn tsc
    - run: npm pack
    - uses: actions/upload-artifact@v3
      with:
        name: package
        path: electron-overlay-window-*.tgz
        retention-days: 3
